# Generated by Django 4.2.2 on 2023-06-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_productinbasket_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='basket', to='user_profile.productinbasket'),
        ),
    ]
