# Generated by Django 4.2.2 on 2023-06-09 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='К какому продукту относится')),
                ('product_photo', models.ImageField(upload_to='photos/product_photo/')),
            ],
            options={
                'verbose_name': 'Фото продукта',
                'verbose_name_plural': 'Фотографии продуктов',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='photos/category_image/subcategory_image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('photos', models.ManyToManyField(to='products.productphoto')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='photos/category_image/', verbose_name='Изображение')),
                ('subcategories', models.ManyToManyField(related_name='category', to='products.subcategory')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
