# Generated by Django 4.2.2 on 2023-06-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='static/products/img/category_image/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='product_photo',
            field=models.ImageField(upload_to='static/products/img/product_photo/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(upload_to='static/products/img/category_image/subcategory_image', verbose_name='Изображение'),
        ),
    ]
