# Generated by Django 4.2.2 on 2023-06-09 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='product_photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
