# Generated by Django 4.2.2 on 2023-06-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_category_subcategories_subcategory_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphoto',
            name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=models.ManyToManyField(related_name='product', to='products.productphoto'),
        ),
    ]
